COMPIL_SERVER = gcc
FLAG_SERVER = -Wall -pthread
NAME_SERVER = server

all: $(NAME_SERVER)

$(NAME_SERVER).o: $(NAME_SERVER).h $(NAME_SERVER).c
	$(COMPIL_SERVER) -c $(FLAG_SERVER) $(NAME_SERVER).c

$(NAME_SERVER): $(NAME_SERVER).o
	$(COMPIL_SERVER) $(FLAG_SERVER) $(NAME_SERVER).o -o $(NAME_SERVER)

clean:
	rm $(NAME_SERVER).o $(NAME_SERVER)
